### ISSUE TITLE
1:1 1.8 melee PvP

### ISSUE THREAD

**Issue by andrewgazelka** [hyperion-mc/hyperion#538]
Let's make sure melee combat is as 1:1 with 1.8 PvP as possible.

* Combat system immunity timeframe issues:
  * Current timeframe feels incorrect
  * Suggestion: Could be around 20 (units/frames?)
* Knockback mechanics:
  * Feels partially correct but has issues
  * Major problem: Allows infinite air combos on players
* Sprinting-related knockback:
  * Knockback calculation doesn't account for sprinting state
  * Issue with sprinting metadata:
    * "IS_SPRINTING" exists in component system
    * Not being tracked/stored properly in metadata
    * Unclear if this is a bug or implementation error

Would you like me to help investigate any of these specific issues? I can assist with reviewing or modifying the combat system code to address these concerns.

**Comment by andrewgazelka** [comment]
@addbounty $50

**Comment by addbounty** [comment]
### Bounty Added: $50 🎉
You've successfully added a bounty of **$50** to this issue. The total bounty is now **$50**.

1. **Tracking the Bounty**: The bounty is now tied to this issue. Contributors can submit PRs to claim it by resolving the issue.
2. **Decay Reminder**: The bounty value decreases by **3% per day** if not claimed.
3. **Completion and Payout**:
   - Once a PR is merged, the bounty system will start a 14-day acceptance window.
4. **Acceptance/Challenge**:
   - The issue author can accept or contest the payout during the window.
   - No response? Auto-acceptance after 14 days. 

Happy bounty hunting! 🚀 

[Signup Banner](https://raw.githubusercontent.com/ghbountybot/assets/refs/heads/main/signup-banner.svg)

**Comment by andrewgazelka** [comment]
btw still figuring the bounty components but will be distributed proportional to # of PRs that do part in fixing this after bounty was made I'm thinking... unless we want any other metric.

**Comment by addbounty** [comment]
### Bounty Added: $50 🎉

You've successfully added a bounty of **$50** to this issue. The total bounty is now **$50**.

1. **Tracking the Bounty**: The bounty is now tied to this issue. Contributors can submit PRs to claim it by resolving
   the issue.
2. **Decay Reminder**: The bounty value decreases by **3% per day** if not claimed.
3. **Completion and Payout**:
    - Once a PR is merged, the bounty system will start a 14-day acceptance window.
4. **Acceptance/Challenge**:
    - The issue author can accept or contest the payout during the window.
    - No response? Auto-acceptance after 14 days.

Happy bounty hunting! 🚀
[Signup Banner](https://raw.githubusercontent.com/ghbountybot/assets/refs/heads/main/signup-banner.svg)

**Comment by andrewgazelka** [comment]
oops 😭

**Comment by Tebarem** [comment]
BTW we fixed the metadata stuff in physics branch

**Comment by andrewgazelka** [comment]
> BTW we fixed the metadata stuff in physics branch

what was the issue?

**Comment by Tebarem** [comment]
for some reason in `hyperion/src/simulation/metadata/mod.rs`

it was 

```rust
observer!(world, flecs::OnSet, &T, [filter] &mut MetadataChanges,).each(|(value, changes)| {
        changes.encode(*value);
});

let register = |view: &mut EntityView<'_>| {
        view.set(T::default());
};
```

to

```rust
world
        .system_named::<(
            &mut (Prev, T),       //            (0)
            &mut T,               //                  (1)
            &mut MetadataChanges, //     (2)
        )>(system_name)
        .multi_threaded()
        .kind::<flecs::pipeline::OnStore>()
        .run(move |mut table| {
            while table.next() {
                unsafe {
                    let mut prev = table.field_unchecked::<T>(0);
                    let prev = prev.get_mut(..).unwrap();

                    let current = table.field_unchecked::<T>(1);
                    let current = current.get(..).unwrap();

                    let mut metadata_changes = table.field_unchecked::<MetadataChanges>(2);
                    let metadata_changes = metadata_changes.get_mut(..).unwrap();

                    // todo(perf): big optimization treating as raw bytes and SIMD
                    // or code that can easily be compiled to SIMD
                    // also can do copy_from_slice in one pass but want SIMD-optimized
                    // first
                    // todo(learn): reborrowing in-depth
                    for (idx, (prev, current)) in itertools::zip_eq(&mut *prev, current).enumerate()
                    {
                        if prev != current {
                            let metadata_changes = metadata_changes.get_unchecked_mut(idx);
                            metadata_changes.encode(*current);
                        }
                    }

                    prev.copy_from_slice(current);
                }
            }
        });

    let register = |view: &mut EntityView<'_>| {
        view.set_pair::<Prev, _>(T::default()).set(T::default());
    };
    ```

and Kump went back to the commit where it this broke it and we just set it back to what it used to be before it broke it. this also broke `/spawn` command but removing the prev and current check fixed it but broke bows

**Comment by Kumpelinus** [comment]
After #696 is merged, it feels like 1.8 PvP. Probably there are some more changes still left todo, but still good job so far everyone :)

**Comment by andrewgazelka** [comment]
> After #696 is merged, it feels like 1.8 PvP. Probably there are some more changes still left todo, but still good job so far everyone :)

yea before closing this probably want to get someone on who is big into PvP and test it with them. I know one such person.


- https://github.com/andrewgazelka/hyperion/issues/707 going to integrate this and then should be easier for people to join

**Comment by addbounty** [comment]
### 🎯 Bounty Completed!

**Time to Completion**: 21h 5m (Dec 13 → Dec 13)

#### 💰 Bounty Details

- **Initial Bounty**: $50.00
- **Final Bounty**: $48.69

---
*Thank you for contributing to open source! The bounty will be transferred after the acceptance window.*

Want to earn bounties too? [Sign up for GHBountyBot](https://github.com/apps/ghbountybot) 🤖

**Comment by andrewgazelka** [comment]
anyway I will consider this effectively completed :) sooooo I just need to figure out how to split the bounty up 😅

**Comment by andrewgazelka** [comment]
good job everyone :)

**Comment by andrewgazelka** [comment]
going to close this. for now
