### ISSUE TITLE
Sneak Bridging doesn't place blocks server side

### ISSUE THREAD

**Issue by GroobleDierne** [hyperion-mc/hyperion#794]
https://github.com/user-attachments/assets/525dc4c1-27c2-4597-8f03-aee0d1483721

**Comment by andrewgazelka** [comment]
hmmmmm I am not 100% sure but it might be an issue that lies beyond sneak bridging. I have had occur a couple times before (but unsure if my case got fixed). probably https://github.com/hyperion-mc/hyperion/tree/main/tools/packet-inspector will help
